---
title: "Notes! Day 2"
author: "Liz Roten"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(usethis)
```

Materials - https://github.com/rstudio-conf-2022/pkg-dev-masterclass


## Leave no error behind  

1. Consistency
1. Transparency
1. Relevance
1. Exhaustiveness
1. Conciseness

Tools
- follow style guide
    - use consistent problem statements -> use "must" and "can't" phrases
- format with CLI
    - additional features, like rlang::abort 
    - uses `{glue}`
    - Action, What, and How
- use error bullets
- pass error calls and arguments
- use chained errors

## Testing, and snapshot tests

- Snapshot tests are for when you don't know the correct output, BUT you know it when you see it. 

- Expected result is captured once and stored as a file within /tests/
- Great for testing messages and errors
- Waldo compare 

- snapshot tests only work in a non-interactive context
- `snapshot_review()`
- snapshots are not testing correctness, they are testing the expectation
    - `transform` takes the snapshot, does something to it, and spits it back out
    - `variant`, like if a function returns system operating info
    - if you want to inspect an error message `expect_snapshot(error = TRUE`)
    - check the class, `expect_error(class = .)`
    - expect the message and check the class, `expect_snapshot_error()`
    
new info
- the `@importFrom` tag can only look for functions that are exported from the given package. 


## Function design 

- Required arguments shouldn't have defaults
- Avoid magical defaults.
- Keep defaults short and sweet
- Explain important defaults
- Enumerate limited input parameters
    - 